### ISSUE TITLE
EMQ Proxy Protocol

### ISSUE THREAD

**Issue by satrox28** [emqtt/emqttd#932] opened 2017-03-03 16:11 UTC
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 1.91
- EMQ: 2.1

#### Description

We have configured a EMQ server and added this server behind an AWS load balancer. When ever the client is connected via LB it shows client IP address as LB address.

Is there a way to get the source IP address.

On AWS LB side I have enabled Proxy Protocol policy and after that the clients are not connecting. Do Emqttd supports Proxy Protocol?.

**Comment by phanimahesh** [comment] 2017-03-03 17:45
Duplicate of #730.

**Comment by emqplus** [comment] 2017-03-10 00:24
@satrox28 I will merge the `Proxy Protocol` PR in 2.2 release.

**Comment by satrox28** [comment] 2017-03-10 01:14
Thanks. May I know when will 2.2 will be released. Is it possible to perform testing now.

**Comment by emqplus** [comment] 2017-03-22 03:28
@satrox28 Please checkout the `emq22` branch for the preview release of Proxy Protocol V1/2 support.

1. Build the `emq22` branch of EMQ:

    git clone -b emq22 https://github.com/emqtt/emq-relx.git
    cd emq-relx && make
    cd _rel/emqttd && ./bin/emqttd console

2. Enable the Proxy Protocol in etc/emq.conf:

    ## Proxy Protocol V1/2
    mqtt.listener.tcp.proxy_protocol = on
    mqtt.listener.tcp.proxy_protocol_timeout = 3s

**Comment by satrox28** [comment] 2017-03-22 10:42
Hi,

Thanks its working now and able to see client IP Address if server behind a load balancer.

Between we see this error on console, what it implies?.

07:56:48.136 [error] Supervisor 'esockd_connection_sup - <0.1159.0>' had child connection started with emqttd_client:start_link([{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,...}]) at <0.2728.19> exit with reason proxy_proto_timeout in context connection_crashed
07:56:48.136 [error] CRASH REPORT Process <0.2727.19> with 0 neighbours crashed with reason: proxy_proto_timeout in esockd_connection:upgrade/1 line 122
07:56:48.136 [error] Supervisor 'esockd_connection_sup - <0.1159.0>' had child connection started with emqttd_client:start_link([{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,...}]) at <0.2727.19> exit with reason proxy_proto_timeout in context connection_crashed

**Comment by emqplus** [comment] 2017-03-22 10:48
@satrox28 The logs mean some MQTT clients connect to the broker directly, not LB.

**Comment by noordawod** [comment] 2017-04-22 11:25
Same issue I had on my end as well. Certain clients need to connect directly without the use of Proxy Protocol. And based on a response by the EMQ team ([see here](https://github.com/emqtt/emqttd/issues/730#issuecomment-289366049)) this can be fixed using just one EMQ instance.

I haven't checked it though, so maybe you can do that @satrox28 and report back?

**Comment by emqplus** [comment] 2017-05-06 14:45
@noordawod @satrox28 The proxy protocol support has been merged to master and released in 2.2-beta.1.

**Closed by emqplus** 2017-05-06 14:45 UTC
Labels: enhancement, In Progress

**Comment by satrox28** [comment] 2017-05-15 07:24
I tried using the 2.2-beta.1,  I am able to connect on 8083,1883 with proxy_protocol enabled on loadbalancer AWS.


May I know why am receiving the below error.


2017-05-15 07:16:33.367 [error] <0.1911.0> CRASH REPORT Process <0.1911.0> with 0 neighbours crashed with reason: {invalid_proxy_info,<<16,51,0,6,77,81,73,115,100,112,3,22,0,15,0,10>>} in esockd_connection:upgrade/1 line 122
2017-05-15 07:16:33.368 [error] <0.1248.0> Supervisor 'esockd_connection_sup - <0.1248.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1911.0> exit with reason {invalid_proxy_info,<<16,51,0,6,77,81,73,115,100,112,3,22,0,15,0,10>>} in context connection_crashed
2017-05-15 07:17:38.739 [error] <0.1948.0> CRASH REPORT Process <0.1948.0> with 0 neighbours crashed with reason: {invalid_proxy_info,<<16,51,0,6,77,81,73,115,100,112,3,22,0,15,0,10>>} in esockd_connection:upgrade/1 line 122
2017-05-15 07:17:38.740 [error] <0.1248.0> Supervisor 'esockd_connection_sup - <0.1248.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1948.0> exit with reason {invalid_proxy_info,<<16,51,0,6,77,81,73,115,100,112,3,22,0,15,0,10>>} in context connection_crashed

**Comment by ajay-aggarwal** [comment] 2017-06-07 12:26
Is there a hook available for on_tcp_connect() with haproxy support? It would be nice to accept/reject the incoming connection based on the client IP and Certificate CN info presented via haproxy protocol.

**Comment by arihantdaga** [comment] 2018-05-22 11:12
I am still facing this issue- 
Got this in logs - 
```
2018-05-22 11:05:08.279 [error] <0.1551.0> Supervisor 'esockd_connection_sup - <0.1551.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.3110.0> exit with reason {invalid_proxy_info,<<16,105,0,4,77,81,84,84,4,194,0,10>>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-05-22 11:05:09.467 [error] <0.3111.0> CRASH REPORT Process <0.3111.0> with 0 neighbours crashed with reason: {invalid_proxy_info,<<16,105,0,4,77,81,84,84,4,194,0,10>>} in esockd_connection:upgrade/1 line 122
2018-05-22 11:05:09.467 [error] <0.1551.0> Supervisor 'esockd_connection_sup - <0.1551.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.3111.0> exit with reason {invalid_proxy_info,<<16,105,0,4,77,81,84,84,4,194,0,10>>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-05-22 11:05:10.733 [error] <0.3112.0> CRASH REPORT Process <0.3112.0> with 0 neighbours crashed with reason: {invalid_proxy_info,<<16,105,0,4,77,81,84,84,4,194,0,10>>} in esockd_connection:upgrade/1 line 122
2018-05-22 11:05:10.734 [error] <0.1551.0> Supervisor 'esockd_connection_sup - <0.1551.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.3112.0> exit with reason {invalid_proxy_info,<<16,105,0,4,77,81,84,84,4,194,0,10>>} in esockd_connection:upgrade/1 line 122 in context connection_crashed


```

If i enable proxy_protocol . I have verified, no client is directly connecting to the broker, every request is coming from the Haproxy itself. I am using EMQ 2.3.6

**Comment by terry-xiaoyu** [comment] 2018-05-23 01:49
@arihantdaga Make sure you have set `listener.tcp.external.proxy_protocol = on`, and you've also turned on the [proxy protocol feature](http://cbonte.github.io/haproxy-dconv/1.9/configuration.html#5.2-send-proxy) of haproxy.

**Comment by arihantdaga** [comment] 2018-05-23 16:40
@terry-xiaoyu  Great.. (y). Its working..
