### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by frank-montyne** [emqtt/emqttd#935] opened 2017-03-05 07:38 UTC
#### Environment

- OS: Linux (Ubuntu 14.04)
- Erlang/OTP: 19 [erts-8.2] [source-fbd2db2] [64-bit]
- EMQ: 2.07

#### Description

I have about 6 clients constantly sending MQTT messages to the broker. The rate of messages is about 1-2 messages/sec in total. Al of a sudden the broker crashed.

I have attached the crash log. The errors can be found near the end of the crash log and look like:

2017-03-05 00:33:48 =ERROR REPORT====
** Generic server <0.10131.7> terminating 
** Last message in was {keepalive,start,38}
** When Server state == {client_state,{esockd_connection,[{ssl_socket,#Port<0.13372>,{sslsocket,{gen_tcp,#Port<0.13372>,tls_connection,undefined},<0.10136.7>}},#Fun<esockd_transport.3.2626899>,[]]},["10.0.0.200",58,"42932"],{{10,0,0,200},42932},{10,0,0,200},42932,true,running,undefined,#Fun<emqttd_parser.0.27418187>,{proto_state,{{10,0,0,200},42932},#Fun<emqttd_client.0.8804271>,true,<<"00486d88-941c-4df6-a98f-5a7cf8a18587">>,<0.10131.7>,false,4,<<"MQTT">>,undefined,false,undefined,30,1024,<0.5886.0>,undefined,{1488,674028,646574}},[{max_clientid_len,1024},{max_packet_size,65536},{client_idle_timeout,30}],undefined,undefined}
** Reason for termination == 
** {{badmatch,{error,einval}},[{emqttd_keepalive,start,3,[{file,"src/emqttd_keepalive.erl"},{line,33}]},{emqttd_client,handle_info,2,[{file,"src/emqttd_client.erl"},{line,209}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}
...

I have no idea why this happens.
All help is welcome.

I also see there are regular crashes in  the dashboard plugin. These erros can be found in the beginning of the crash log and look like:

2017-03-05 00:32:15 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1050.0>'
     Context:    connection_crashed
     Reason:     {json_encode,{bad_term,{'EXIT',{badarith,[{emqttd_vm,loads,0,[{file,"src/emqttd_vm.erl"},{line,161}]},{emq_dashboard_overview,node_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,77}]},{rpc,local_call,3,[{file,"rpc.erl"},{line,330}]},{emq_dashboard_overview,'-nodes_info/0-lc$^0/1-0-',2,[{file,"src/emq_dashboard_overview.erl"},{line,73}]},{emq_dashboard_overview,nodes_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,73}]},{emq_dashboard,'-dispatcher/1-fun-3-',4,[{file,"src/emq_dashboard.erl"},{line,52}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,75}]}]}}}}
     Offender:   [{pid,<0.1324.0>},{name,connection},{mfargs,{mochiweb_http,start_link,[{emq_dashboard,handle_request,[{state,"/usr/lib/emqttd/lib/emq_dashboard-2.0.7/priv/www",#Fun<emq_dashboard.1.76099874>}]}]}}]

Best regards,
Frank Montyne
byNubian BVBA

[crash.log.zip](https://github.com/emqtt/emqttd/files/819185/crash.log.zip)

**Comment by frank-montyne** [comment] 2017-03-05 07:45
I forget to mention that I'm using an SSL connection to the broker

Best regards,
Frank Montyne

**Comment by phanimahesh** [comment] 2017-03-05 09:44
It looks like a few processes crashed, not the broker. Process crashes are considered normal in erlang, since we rely on built in recovery and self healing mechanisms and let processes crash when they do not behave well.

Can you confirm the maximum packet size you are sending? Is the error reproducible under some conditions reliably? If yes, can you describe how to reproduce this?

The first crash looks like the connection was unable to report its stats for some reason. `src/emqttd_client.erl:250` probably returns error which then causes a `badmatch` in `emqttd_keepalive:start/3`. This may be because the socket closed or connection died unexpectedly, or might be a bug/unhandled case with some connection handling code.

Regarding the second crash log, is `/proc` mounted and accessible by your emqttd? Looks like `cpu_sup` wasn't able to determine the load average for some reason. This crash can be ignored safely. It won't affect the broker's performance or behaviour, only some stats in the dashboard may not be populated.

**Comment by frank-montyne** [comment] 2017-03-05 11:53
Hi,

The maximum packet size per message is about 150-200 bytes well below the 64K max packet size.
It's the first time I had this type of crash. The problem is that the emqttd process was stopped. Running "sudo service emqttd status" gave "emqttd is stopped".  Seems like the self healing didn't work. 

I installed EMQ using "sudo gdebi emqttd_2.0.7_ubuntu14.4_amd64.deb". 
/proc is mounted. 
I tried "sudo -u emqtt cat /proc/cpuinfo" to check if emqtt has access to /proc and that command gave me the cpu information back.

**Comment by phanimahesh** [comment] 2017-03-05 17:08
That seems like a bigger issue then. Is the crash log you posted the full one? Anything else you can find in syslogs, maybe? Is emqttd being killed by OS due to resource scarcity?

For anyone else looking at this, looks like `{error, einval}` is from `Conn:getopt([recv_oct])`. Digging into esockd and down shows the ultimate calls are to either `inet:getopt/2` or `ssl:getopt/2`, and the error is due to an invalid argument. Since the options `[recv_oct]` is valid, it means the connection socket is bad. Stale socket, maybe?

@frank-montyne Can you help reproduce this issue? I'm running 2.0.7 since a couple of weeks and haven't seen this issue.

**Comment by frank-montyne** [comment] 2017-03-05 18:26
I'll see if I can reproduce the crash.

I uploaded a recent console and error log. I see that there are sometimes warnings and errors. Perhaps it is related to these?

[console&error-log.zip](https://github.com/emqtt/emqttd/files/819599/console.error-log.zip)

**Comment by frank-montyne** [comment] 2017-03-06 09:14
Hi,

The emqtt process crashed again last night. I uploaded my emq.conf and some more log files. The console log contains information at the INFO level. It gives you a better idea of the data packets that are coming in. I'm constantly running EMQ with:

log.console.level = info

because I want a complete trace of what's going on, that should not be a problem I guess?

[logs-and-conf.zip](https://github.com/emqtt/emqttd/files/820599/logs-and-conf.zip)

**Comment by emqplus** [comment] 2017-03-06 10:01
Hi @frank-montyne, I checked all the log files you attached. No hints for the crash. If the Erlang VM crashed, there will be a log/crash.dump file generated. I guess the Erlang process is killed by OS. Please check the syslog at the same time.

**Comment by frank-montyne** [comment] 2017-03-06 12:15
Hi,

I don't see a crash.dump file. There is also nothing to see in the syslog files> Nevertheless the emqtt proces was stopped! The weird thing is it seems to stop exactly at 1 AM each time.

**Comment by phanimahesh** [comment] 2017-03-06 12:40
Does the server restart at 1? Anything in cron? Anything that may trigger
an oom at 1?

**Comment by frank-montyne** [comment] 2017-03-06 14:03
There is nothing specifically scheduled at 1 PM that  I know of. We used to run mosquitto (until last week) on that server and we never had any problems. I installed EMQ using gdebi that's all.
I added the syslogs. Nothing special except for some manual restarts from me.

Crontab contains the following entries:
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

[syslog.zip](https://github.com/emqtt/emqttd/files/821340/syslog.zip)

**Comment by frank-montyne** [comment] 2017-03-06 14:10
I looked again for a crash.dump file on the whole disk but I didn't find any.

sudo find / -name *crash* only list the following:

/usr/share/doc/apport/crashdb-conf.txt.gz
/usr/share/apport/kernel_crashdump
/usr/share/apport/testsuite/test_signal_crashes.pyc
/usr/share/apport/testsuite/test_signal_crashes.py
/usr/share/apport/testsuite/test_java_crashes.py
/usr/share/apport/testsuite/test_java_crashes.pyc
/usr/share/apport/testsuite/crash.class
/usr/share/apport/testsuite/crash.jar
/usr/share/apport/testsuite/test_crash_digger.pyc
/usr/share/apport/testsuite/test_crashdb.py
/usr/share/apport/testsuite/test_crash_digger.py
/usr/share/apport/testsuite/test_python_crashes.py
/usr/share/apport/testsuite/test_python_crashes.pyc
/usr/share/apport/testsuite/test_crashdb.pyc
/usr/lib/python3/dist-packages/apport/crashdb_impl
/usr/lib/python3/dist-packages/apport/__pycache__/crashdb.cpython-34.pyc
/usr/lib/python3/dist-packages/apport/crashdb.py
/usr/lib/python2.7/dist-packages/twisted/test/crash_test_dummy.py
/usr/lib/python2.7/dist-packages/twisted/test/crash_test_dummy.pyc
/usr/lib/emqttd/lib/observer-2.1.2/ebin/crashdump_viewer.beam
/usr/lib/emqttd/lib/observer-2.1.2/priv/crashdump_viewer.tool
/usr/lib/emqttd/lib/observer-2.1.2/priv/crashdump_viewer
/usr/lib/emqttd/lib/lager-3.2.2/ebin/lager_crash_log.beam
/usr/lib/emqttd/log/crash.log.3
/usr/lib/emqttd/log/crash.log
/usr/lib/emqttd/log/crash.log.0
/usr/lib/emqttd/log/crash.log.1
/usr/lib/emqttd/log/crash.log.4
/usr/lib/emqttd/log/crash.log.2
/usr/src/linux-headers-3.16.0-31/include/linux/crash_dump.h
/usr/src/linux-headers-3.16.0-31-generic/include/config/crash
/var/crash
/sys/devices/system/cpu/cpu0/crash_notes
/sys/devices/system/cpu/cpu0/crash_notes_size
/sys/kernel/kexec_crash_size
/sys/kernel/kexec_crash_loaded
/etc/apport/crashdb.conf

**Comment by phanimahesh** [comment] 2017-03-06 15:33
These are of interest to us:

/usr/lib/emqttd/log/crash.log.3
/usr/lib/emqttd/log/crash.log
/usr/lib/emqttd/log/crash.log.0
/usr/lib/emqttd/log/crash.log.1
/usr/lib/emqttd/log/crash.log.4
/usr/lib/emqttd/log/crash.log.2

Any chance you can share some of them after anonymising any sensitive info?

**Comment by phanimahesh** [comment] 2017-03-06 15:35
Ignore that, the ones you shared previously are good enough if that or
similar entries are all they have.

**Comment by frank-montyne** [comment] 2017-03-06 18:42
Yes that's it.

**Comment by frank-montyne** [comment] 2017-03-07 09:07
Hi,

This night I had the problem again but slightly different. When I woke up this morning I saw that my service was not receiving any messages anymore from the broker. The broker however was still running. It was receiving messages from our nodes (hardware devices sending MQTT messages to specific topics) but it was not publishing them anymore to my service that is subscribed to these topics. The broker was using 100% cpu. I took some screenshots for you:

The first shows a view with htop where you can see the emqttd process taking up all cpu. 

The seconds screenshot is from the dashboard that shows the broker is using a lot of memory (up from around 60 MB under normal circumstances but now at around 400MB). It was still receiving messages since the received count was still going up (314904 at the moment of the screenshot) but only 254494 were already delivered. The sent count did ot go up anymore, it stayed fixed at the 254494 count. So around 60000 still needed to be published (and going up). 

The third screenshot is from my service, I restarted the service just to make sure but no messages were coming in. I had to stop the broker process and restart it (losing 60000 messages in the process) before things went back to normal.
[screenshots.zip](https://github.com/emqtt/emqttd/files/823848/screenshots.zip)

**Comment by phanimahesh** [comment] 2017-03-08 19:55
I'm considering the options on how this can be reproduced. Are you comfortable with erlang? It is possible to inspect the emqttd instance when it reaches this state, and that can be helpful. Specifically, we need to look at erlang process count and if there is a process leak, possibility of a binary leak, and average message queue length of processes and how it varies.

Do you have or can you arrange for trends of cpu, ram and network usage for one night when this happens? The graphs may hold a clue.

My current blind bet: EMQ dispatcher is going wonky, or client/session processes are getting locked up on something.

**Comment by frank-montyne** [comment] 2017-03-08 21:49
Hi,
I'm not really comfortable with Erlang. Yesterday I wrote a load tester in
java to try and crash the EMQ broker. I let it run simulating 100 clients
each sending 1000 messages/minute and could not make the broker crash.
Tomorrow (almost midnight in Belgium) we are going to do a test with with
our hardware device and see if that triggers the crash. If that works I can
setup a VM with EMQ on Azure and give you access to it to replicate the
test again. What do you think?

Up until now we were using mosquitto and we never had any real problems. We
processed about 100.000.000 messages in the last year coming from our
hardware.
If you want to know more about what we do you can have a look on our
website (www.bynubian.com)

Best regards,
Frank Montyne

**Comment by phanimahesh** [comment] 2017-03-09 04:54
To crash emqttd using just number of messages shouldn't be possible
technically. (tm). You can happily increase the load a hundred fold or more
and it should be absorbed. Things may slow down if your hardware is on the
low end, but that should be it.

If this can be replicated in a VM, that would be great. I'll take out some
time to help debug this if I can get my hands on emqttd when it misbehaves.

**Comment by frank-montyne** [comment] 2017-03-09 07:26
Cool thanks, working on setting something up today.

**Comment by emqplus** [comment] 2017-03-09 07:53
@frank-montyne The benchmark report provided by XMeter: http://emq-xmeter-benchmark-en.readthedocs.io/en/latest/ 

I still cannot figure out why your deployment crashed when there are still too few clients and messages:(

**Comment by frank-montyne** [comment] 2017-03-13 13:46
Hi, 
I meanwhile added some logging and did some further tests. Apparently what happened is the following:

1. At some point in time my persistence service that is subscribed to a number of topics loses its connection to the EMQ broker. The reason why is still unclear. 
2. My service gets notified of the lost connection and starts a background task to reconnect.
3. For some bizarre reason the reconnect succeeds immediately and I also get a disconnect just afterwards. Then we go into a loop of connects/disconnects. I never had this behaviour with Mosquitto.
4. Eclipse Paho has an auto reconnect feature itself. I didn't use that up until now because I wanted a bi more control over the reconnect process. I adjusted the code to use that and up until now I had no problems anymore.  Quite weird since it basically does the same thing.

Any ideas about this connect/disconnect loop?
Thanks,
Frank

**Comment by emqplus** [comment] 2017-03-14 02:07
@frank-montyne ClientId conflicts.

**Comment by frank-montyne** [comment] 2017-03-14 11:16
What do you mean? The disconnected client just reconnects with the same client id. Otherwise it would lose its subscriptions.

**Comment by phanimahesh** [comment] 2017-03-15 23:04
@frank-montyne At any point of time, if two clients connect with the same client id, the older one gets kicked out. If both of them attempt reconnections immediately, you get the behaviour you describe.

Client id conflicts are disallowed in MQTT specification. I'm sure mosquitto prevents duplicate client ids, most likely following the same behaviour. (An alternate option is to reject the new client)

How are your client ids being generated? Are you letting any framework/library autogenerate them, or are you assigning them using your own scheme? If you rolled your own scheme, what is it? Looking at the logs, you should also see ip and username assosciated with the clients. Or you can trace using `emqttd_ctl trace client <client_id> <filename>` to see detailed tracess for a particular client id.

Identify the bad client and have its client id changed to fix this issue.

**Comment by frank-montyne** [comment] 2017-03-16 10:26
All my clients use a unique UUID (globally unique identifier) that is fixed. This means that if you get a client with the same id it effectively is the same client.  The reason I was reconnecting is because at some point in time Paho notifies me that the connection is broken. At that point I initialize a new Paho client with the same client id (because I don't want to lose my subscriptions) and try to connect again. When I was using Mosquitto that worked without any problems, probably because Mosquitto just cleans up the stale connection.
For EMQ I am now using the autoreconnect feature of Paho instead to avoid getting into trouble.

**Comment by phanimahesh** [comment] 2017-03-16 10:57
In that case both mosquitto and EMQ kick the older client if it exists and use the newly connected client for the session. I verified MQTT specifications and this is MUST. All brokers will disconnect existing client and allow newly connected one to take over the session.

When paho notifies that the connection is broken, do you ensure that it is teared down completely before reinitiating connection? If Paho is connecting again automatically, when you create a new connection it can cause the conflict. Is this Paho js or Paho Java? Any example code that you can provide to reproduce the issue?

**Comment by emqplus** [comment] 2017-03-21 03:46
@frank-montyne Could we close the issue now?

**Comment by frank-montyne** [comment] 2017-03-21 08:56
Its Java Paho. Probably the auto reconnect feature of Paho does a better job of cleaning up the stale connection. This issue can be closed. The EMQ broker has been working flawlessly for the last 12 days.

Thanks for the support,
Frank

**Comment by emqplus** [comment] 2017-03-21 09:01
@frank-montyne Thanks.

**Closed by emqplus** 2017-03-21 09:01 UTC
Labels: BUG, Support, wontfix
