### ISSUE TITLE
Duplicate message delivery to subscribers on a node crash in emqttd cluster

### ISSUE THREAD

**Issue by abhidtu** [emqtt/emqttd#399] opened 2015-12-05 19:52 UTC
Hi erylee,
Messages already delivered are getting delivered each time a node crashes and connects to other node in the cluster.
I am using clean session = false and retain true
emqttd version 0.13

Suppose we have two nodes in cluster
node - 1 : emqttd@52.15.55.22
node - 2:  emqttd@52.22.55.44

steps to reproduce these issues - 
occurs always - 
step 1 - A client id ("test1") is connected to any one of these nodes (suppose node - 1).
step 2 - "test1" subscribes to channel "abc"
step 3 - publish some messages on "abc"
step 4 - node - 1 crashes (stopping emqttd server on that node or killing beam.smp erlang process)
step 5 - connect the same client "test1" to node - 2 
step 6 - subscribe to channel "abc"
step 7 - start the node 1 in meantime (recovery)
step 8 - node - 2 crashes (stopping emqttd server on that node or killing beam.smp erlang process) 
step 9 - connect to node 1 again 
step 10 - subscribe to channel "abc"
step 11 - all the messages already delivered to "test 1" on "abc"are  delivered again to "test1".

occurs frequently -
step 1 - A client id ("test1") is connected to any one of these nodes (suppose node - 1).
step 2 - "test1" subscribes to channel "abc"
step 3 - publish some messages on "abc"
step 4 - node - 1 crashes (stopping emqttd server on that node or killing beam.smp erlang process)
step 5 - connect the same client "test1" to node - 2
step 6 - subscribe to channel "abc"
step 7 - all the messages  delivered to "test 1" on "abc"are delivered again to "test1".

This keeps on happening again and again if we keep on repeating the above steps.

**Comment by erylee** [comment] 2015-12-08 02:57
Hi @abhidtu, this is not a bug, the 'retain=true' message will be stored and redelivered. Please check MQTT specification.

**Comment by erylee** [comment] 2015-12-09 02:25
hi @abhidtu, have you read the specification about the 'retain' flag?  could we close this issue now?

**Comment by abhidtu** [comment] 2015-12-09 16:38
Hi @erylee thanks replying,
I went through the MQTT specification and now after setting retain = false this thing is not happening.

But According to the specification:
If the RETAIN flag is set to 1, in a PUBLISH Packet sent by a Client to a Server, the Server MUST store the Application Message and its QoS, so that it can be delivered to "future subscribers" whose subscriptions match its topic name [MQTT-3.3.1-5]. When a "new subscription" is established, the last retained message, if any, on each matching topic name MUST be sent to the subscriber [MQTT-3.3.1-6].

If you see clientId : "test1" was already subscribed on a topic "abc" to one of the nodes in the cluster which means that "test1" is already an "old subscriber" on this topic.

I think why this is happening is because if a node crashes and the client connects to a new node in the cluster, now it becomes a "new subscriber" for that node and that's why the messages gets redelivered if the retain flag = true even though this client was an old subscriber in the cluster.

I think this retain = true/false thing should work across cluster such that even if a client connects to a new node in the cluster in case of a node crash there should be some memory which should maintain that this node was already subscribed to this channel ("abc") on crashed node and it is not a new subscriber on this node.

What do you think about this?

**Comment by erylee** [comment] 2015-12-10 14:58
@abhidtu, current design of the retained message is appropriate, I think.

First, the retained messages we published to one node, should be received by clients connected to other nodes in the cluster. So each node in the cluster will replicate the retained messages.

Second, if a node crashed,  the session and subscriptions of a client will be removed by the broker. And the same client connected to another node later will be treated as a new one.

**Comment by abhidtu** [comment] 2015-12-10 16:45
@erylee, thanks for replying,
We can close this issue then.

**Closed** 2015-12-11 15:08 UTC
Labels: Discussion, invalid
