### ISSUE TITLE
Cannot load redis auth plugin 

### ISSUE THREAD

**Issue by tu226** [emqtt/emqttd#1488] opened 2018-02-02 08:44 UTC
#### Environment

- OS:  CentOS 6.5
- Erlang/OTP: 
- EMQ: 2.3.4

#### Description
cannot load redis auth plugin when the config file has a password which contains ':', 
for example:
```
auth.redis.password = crs-xxx:abc456
```

**Comment by huangdan** [comment] 2018-02-03 06:09
@terry-xiaoyu Cannot reproduce the issue, Please provide more logs to find out the issue.

**Comment by tu226** [comment] 2018-02-05 03:11
2018-02-02 16:03:47.318 [error] <0.1511.0> Supervisor {<0.1511.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_redis, 1, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in context start_error
2018-02-02 16:03:47.318 [error] <0.1509.0> Supervisor {<0.1509.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}} in context start_error
2018-02-02 16:03:47.318 [error] <0.1508.0> Supervisor emq_auth_redis_sup had child emq_auth_redis started with ecpool:start_pool(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}} in context start_error
2018-02-02 16:03:47.319 [error] <0.1504.0>@emqttd_plugins:start_app:164 load plugin emq_auth_redis error, cannot start app emq_auth_redis for {bad_return,{{emq_auth_redis_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}}},[{emq_auth_redis_app,start,2,[{file,"src/emq_auth_redis_app.erl"},{line,26}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
2018-02-02 16:03:47.319 [error] <0.1506.0> CRASH REPORT Process <0.1506.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}} in emq_auth_redis_app:start/2 line 26 in application_master:init/4 line 134
2018-02-02 16:03:58.399 [error] <0.1523.0> CRASH REPORT Process <0.1523.0> with 0 neighbours exited with reason: {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in gen_server:init_it/6 line 349
2018-02-02 16:03:58.399 [error] <0.1522.0> CRASH REPORT Process <0.1522.0> with 0 neighbours exited with reason: {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in gen_server:init_it/6 line 349
2018-02-02 16:03:58.399 [error] <0.1521.0> Supervisor {<0.1521.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_redis, 1, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in context start_error
2018-02-02 16:03:58.399 [error] <0.1519.0> Supervisor {<0.1519.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}} in context start_error
2018-02-02 16:03:58.399 [error] <0.1518.0> Supervisor emq_auth_redis_sup had child emq_auth_redis started with ecpool:start_pool(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}} in context start_error
2018-02-02 16:03:58.400 [error] <0.1516.0> CRASH REPORT Process <0.1516.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}} in emq_auth_redis_app:start/2 line 26 in application_master:init/4 line 134
2018-02-02 16:03:58.400 [error] <0.1514.0>@emqttd_plugins:start_app:164 load plugin emq_auth_redis error, cannot start app emq_auth_redis for {bad_return,{{emq_auth_redis_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}}},[{emq_auth_redis_app,start,2,[{file,"src/emq_auth_redis_app.erl"},{line,26}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
2018-02-02 16:04:32.767 [error] <0.1526.0>@emqttd_protocol:process:234 Client(4_999999_ctest1@58.250.17.19:9347): Username 'yqjpCloudServer' login failed for "No auth module to check!"
2018-02-02 16:04:43.451 [error] <0.1530.0>@emqttd_protocol:process:234 Client(4_999999_ctest2@58.250.17.19:9351): Username 'yqjpCloudServer' login failed for "No auth module to check!"
2018-02-02 16:04:45.511 [error] <0.1540.0> CRASH REPORT Process <0.1540.0> with 0 neighbours exited with reason: {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in gen_server:init_it/6 line 349
2018-02-02 16:04:45.511 [error] <0.1539.0> CRASH REPORT Process <0.1539.0> with 0 neighbours exited with reason: {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in gen_server:init_it/6 line 349
2018-02-02 16:04:45.511 [error] <0.1531.0>@emqttd_plugins:start_app:164 load plugin emq_auth_redis error, cannot start app emq_auth_redis for {bad_return,{{emq_auth_redis_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}}},[{emq_auth_redis_app,start,2,[{file,"src/emq_auth_redis_app.erl"},{line,26}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
2018-02-02 16:04:45.511 [error] <0.1538.0> Supervisor {<0.1538.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_redis, 1, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in context start_error
2018-02-02 16:04:45.511 [error] <0.1536.0> Supervisor {<0.1536.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}} in context start_error
2018-02-02 16:04:45.512 [error] <0.1535.0> Supervisor emq_auth_redis_sup had child emq_auth_redis started with ecpool:start_pool(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}} in context start_error
2018-02-02 16:04:45.512 [error] <0.1533.0> CRASH REPORT Process <0.1533.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}} in emq_auth_redis_app:start/2 line 26 in application_master:init/4 line 134
2018-02-02 16:05:31.823 [error] <0.1549.0>@emqttd_protocol:process:234 Client(4_999999_ctest1@58.250.17.19:9372): Username 'yqjpCloudServer' login failed for "No auth module to check!"
2018-02-02 16:05:38.764 [error] <0.1561.0> CRASH REPORT Process <0.1561.0> with 0 neighbours exited with reason: {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in gen_server:init_it/6 line 349
2018-02-02 16:05:38.764 [error] <0.1560.0> CRASH REPORT Process <0.1560.0> with 0 neighbours exited with reason: {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in gen_server:init_it/6 line 349
2018-02-02 16:05:38.765 [error] <0.1559.0> Supervisor {<0.1559.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_redis, 1, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}} in context start_error
2018-02-02 16:05:38.765 [error] <0.1557.0> Supervisor {<0.1557.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}} in context start_error
2018-02-02 16:05:38.765 [error] <0.1556.0> Supervisor emq_auth_redis_sup had child emq_auth_redis started with ecpool:start_pool(emq_auth_redis, emq_auth_redis_cli, [{pool_size,8},{auto_reconnect,1},{host,"10.3.13.5"},{port,6379},{database,10},{password,"crs-hp..."}]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}} in context start_error
2018-02-02 16:05:38.765 [error] <0.1554.0> CRASH REPORT Process <0.1554.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid password\r\n">>}}}}}}}}}} in emq_auth_redis_app:start/2 line 26 in application_master:init/4 line 134
2018-02-02 16:05:38.764 [error] <0.1552.0>@emqttd_plugins:start_app:164 load plugin emq_auth_redis error, cannot start app emq_auth_redis for {bad_return,{{emq_auth_redis_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{authentication_error,{unexpected_data,{ok,<<"-ERR invalid

**Comment by huangdan** [comment] 2018-02-05 03:41
@tu226, Are you sure that `auth.redis.password` in emq_auth_reids.conf is same as `requirepass` in redis.conf?

**Comment by tu226** [comment] 2018-02-05 03:45
I sure used follow password as sams as another project which has no problem 
crs-hp1n6w0b:jpyp123456

**Comment by emqplus** [comment] 2018-02-05 05:11
@tu226 Please attach your `etc\plugins\emq_auth_redis.conf` and `redis.conf`

**Comment by tu226** [comment] 2018-02-05 05:39
##--------------------------------------------------------------------
## Redis Auth/ACL Plugin
##--------------------------------------------------------------------

## Redis server address.
##
## Value: Port | IP:Port
##
## Examples: 6379, 127.0.0.1:6379, localhost:6379
auth.redis.server = 10.3.13.5:6379

## Redis pool size.
##
## Value: Number
auth.redis.pool = 8

## Redis database no.
##
## Value: Number
auth.redis.database = 10

## Redis password.
##
## Value: String
auth.redis.password = crs-hp1n6w0b:jpyp123456

## Authentication query command.
##
## Value: Redis cmd
##
## Variables:
##  - %u: username
##  - %c: clientid
##
## Examples:
##  - HGET mqtt_user:%u password
##  - HMGET mqtt_user:%u password
##  - HMGET mqtt_user:%u password salt
auth.redis.auth_cmd = HGET emq.cloudUser:%u password

## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
auth.redis.password_hash = plain

## sha256 with salt prefix
## auth.redis.password_hash = salt,sha256

## sha256 with salt suffix
## auth.redis.password_hash = sha256,salt

## bcrypt with salt prefix
## auth.redis.password_hash = salt,bcrypt

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.redis.password_hash = pbkdf2,sha256,1000,20

## Superuser query command.
##
## Value: Redis cmd
##
## Variables:
##  - %u: username
##  - %c: clientid
auth.redis.super_cmd = HGET emq.cloudUser:%u is_superuser

## ACL query command.
##
## Value: Redis cmd
##
## Variables:
##  - %u: username
##  - %c: clientid
auth.redis.acl_cmd = HGETALL emq.cloudAcl:%u

there is only an emq_auth_redis.conf

**Comment by huangdan** [comment] 2018-02-05 06:40
@tu226, You can try to execute the following command on the Redis Server: 
`redis-cli -h 10.3.13.5 -n 10 -a crs-hp1n6w0b:jpyp123456`

**Comment by tu226** [comment] 2018-02-05 07:09
redis-cli -h 10.3.13.5 -n 10 -a crs-hp1n6w0b:jpyp123456 

can not auth,must has port param

redis-cli -h 10.3.13.5 -n 10 -p 6379 -a crs-hp1n6w0b:jpyp123456 (no problem)

**Comment by huangdan** [comment] 2018-06-11 10:08
@tu226 Close it now and reopen it if you still have any questions.

**Closed by huangdan** 2018-06-11 10:08 UTC
Labels: Support
