### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by ameyaapte1** [emqtt/emqttd#1284] opened 2017-10-09 13:41 UTC
#### Environment

- OS: Fedora 22
- Erlang/OTP: N/A
- EMQ: Latest clone

#### Description

fatal: repository 'https://github.com/emqtt/emq-lwm2m/' not found
The build is failing with the above error

**Comment by ameyaapte1** [comment] 2017-10-09 13:57
Temporary solution:
remove emq_lwm2m from DEPS in Makefile

**Comment by emqplus** [comment] 2017-10-09 15:15
@ameyaapte1, we introduced a `emqx` organization which helps build a IoT messaging platform based on EMQ.  The `emq-lwm2m` project has been moved to `emqx/emqx-lwm2m` and will be released in 2.4-beta.1

**Comment by asciijungle** [comment] 2017-10-11 13:55
I can confirm the bug using commit e1d8c1603c75c507eba30f184b886a84602f16c1 from September 12th. 

```
 DEP    emq_lwm2m
fatal: could not read Username for 'https://github.com': No such device or address
/bin/sh: cd: line 1: can't cd to /emqttd/deps/emq_lwm2m
make: *** [erlang.mk:814: /emqttd/deps/emq_lwm2m] Error 2
```

**Comment by asciijungle** [comment] 2017-10-11 14:04
The problem is that the emq-lwm2m is gone from github. Maybe renamed?
The project's github page can be found on google but it results in a HTTP-404: https://github.com/emqtt/emq-lwm2m

Still available in the cache though: https://webcache.googleusercontent.com/search?q=cache:avCZ8ZUjuKMJ:https://github.com/emqtt/emq-lwm2m+

**Comment by emqplus** [comment] 2017-10-12 02:45
@asciijungle The `EMQ` organization will focus on MQTT messaging broker. So we moved the `emq_lwm2m` project to `emqx` organization, which is aimed to provide a scalable messaging platform for IoT applications. 

You can pull the latest master branch to build the 2.3-rc.1 release, or remove the `emq_lwm2m` DEP in Makefile and relx.config from `emqx-relx` project.

**Comment by asciijungle** [comment] 2017-10-13 08:22
thanks @emqplus that's what I did.

**Closed** 2017-10-21 10:51 UTC
Labels: BUG
