### ISSUE TITLE
File operation error: emfile

### ISSUE THREAD

**Issue by callbay** [emqtt/emqttd#445] opened 2016-02-04 01:38 UTC
emqtt_bench_pub -c 1000 -I 10 -t bench/%i -s 256

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
File operation error: emfile. Target: /Users/frank/emqttd/rel/emqttd/lib/gen_logger-1.0/ebin/lager_logger.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
File operation error: emfile. Target: lager_logger.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
File operation error: emfile. Target: /Users/frank/emqttd/rel/emqttd/lib/gen_logger-1.0/ebin/lager_logger.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
File operation error: emfile. Target: lager_logger.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
File operation error: emfile. Target: /Users/frank/emqttd/rel/emqttd/lib/gen_logger-1.0/ebin/lager_logger.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
File operation error: emfile. Target: lager_logger.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Feb-2016::15:51:48 ===
** Generic server <0.296.0> terminating 
** Last message in was {inet_async,#Port<0.6121>,63875,{error,emfile}}
** When Server state == {state,#Port<0.6121>,
                               #Fun<esockd_transport.2.94509882>,
                               #Fun<esockd_listener_sup.1.16895020>,
                               ["0.0.0.0",58,"1883"],
                               <0.280.0>,#Fun<esockd_server.0.76791649>,
                               {gen_logger,lager_logger,8},
                               63875,0}
** Reason for termination == 
** {'module could not be loaded',
       [{lager_logger,error,
            ["acceptor on ~s suspend 100(ms) for ~p emfile errors!!!",
             [["0.0.0.0",58,"1883"],0]],
            []},
        {esockd_acceptor,sockerr,2,
            [{file,"src/esockd_acceptor.erl"},{line,169}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

**Comment by erylee** [comment] 2016-02-15 18:44
The issue caused by incorrect 'ulimit -n' setting. I will change the default 'max_clients' of the broker to 512.

**Comment by emqplus** [comment] 2016-06-01 03:08
@callbay, The issue is fixed in gen_logger library: https://github.com/emqtt/esockd/issues/25

**Closed by emqplus** 2016-06-01 03:08 UTC
Labels: Discussion
