### ISSUE TITLE
How can i use SSL/TLS certificate based client authentication ?

### ISSUE THREAD

**Issue by msdevanms** [emqtt/emqttd#794] opened 2016-12-05 13:53 UTC
#### Environment

- OS: Ubuntu 14.04.2 LTS
- Erlang/OTP:  
- EMQ: 

#### Description

Is there any plan to support  certfile and keyfile  based client authentication including certificate revocation ?
Since emqtt supports pretty much all kind of client authentications it will be good to have certificate based SSL/TLS client auth.

While connecting with mosquitto_sub over mosquitto server i am using --cert and --key for specifying these two files.

If this option already available please let me know.

**Comment by emqplus** [comment] 2016-12-06 13:57
@msdevanms Plan to support this feature in 2.1 release.

**Comment by KohliDev** [comment] 2017-06-07 11:49
Isn`t this bug duplicate of #585 ???

**Comment by PiedPieper** [comment] 2017-08-03 17:53
Was this included in 2.1? I cannot find any documentation on this

**Comment by emqplus** [comment] 2017-12-27 06:55
@msdevanms @KohliDev @PiedPieper Duplicated with #1185. The feature is production ready for R 2.3.2 release.

**Closed by emqplus** 2017-12-27 06:55 UTC
Labels: enhancement, High, SSL

**Comment by KohliDev** [comment] 2018-01-01 04:12
Thanks @emqplus

**Comment by rahulfk** [comment] 2018-04-06 09:24
is there any documentation on how this feature works??

**Comment by cocowalla** [comment] 2018-06-06 21:29
I'm also looking for any documentation on how to use x509 client authentication, how to specify trusted issuers, and whether it works when using web sockets?

**Comment by avenetj** [comment] 2018-06-07 12:47
Hi, I'm also looking for such documentation
