### ISSUE TITLE
Cascading multiple authentication modules properly

### ISSUE THREAD

**Issue by vivek1729** [emqtt/emqttd#777] opened 2016-11-26 06:49 UTC
#### Environment

- OS: Mac OS 10.12
- Erlang/OTP: R18/7.3
- EMQ: 2.0

#### Description

I am trying to authenticate users using the HTTP module which works great! However, I have this authentication API on the app server and the MQTT broker sits between the app server and browser. So naturally, the browser and the App server would also need to have an mqtt client subscribing and publishing on topics.

So, I need to have some sort of a superadmin user sitting on the App server. For this purpose I used the username password auth module which worked great in isolation. Remember I can't use the HTTP auth module for the app server client as it hosts the mqtt auth apis itself.

I was also checking the [docs](http://docs.emqtt.com/en/latest/guide.html#authentication) on using different modules together from authentication and gather that it first tries the username/password , then clientId level and then anonymous.

I was hoping if it first checks username, password and then falls back on http api, then it would work for my case. But it doesn't flow like that by default. It checks username and password and therefore fails for the client in the browser. Any idea how to handle this case where I want the app server to be the superadmin and it also hosts the mqtt http authentication API for any other client that connects via web sockets.

I hope I was able to explain my predicament.

**Comment by phanimahesh** [comment] 2017-03-24 17:44
@vivek1729 Did you try returning `ignore` from the acl/auth plugin? EMQ then tries the next one.

Also, I didn't know you were working on mqtt stuff. Cool! Ping to catch up.

**Comment by hachreak** [comment] 2017-03-29 21:10
I'm not sure if the order of checks is predictable.
I mean, it looks like depends on the order how the plugins are loaded.
It will be awesome to be able to define in a deterministic way the order of checks. :smile:

**Comment by hachreak** [comment] 2017-03-29 21:13
p.s. Also the [commit](https://github.com/emqtt/emqttd/commit/4f0bd74f878e42e8a41a26a8355327ff7787efeb) from @turtleDeng could help! :)

**Comment by emqplus** [comment] 2017-03-30 01:36
@hachreak The Cascading of authentication/ACL will be released in 2.2

**Comment by emqplus** [comment] 2017-05-08 04:45
@hachreak @vivek1729 Fixed in 2.2-beta.1 release. Check the issue #889

**Closed by emqplus** 2017-05-08 04:45 UTC
Labels: enhancement

**Comment by jlgm** [comment] 2017-11-29 21:46
@emqplus @hachreak Is the order of checks determined by the order in which the plugins were loaded? My tests indicate yes but I wasn't able to confirm.

**Comment by manick02** [comment] 2018-02-26 12:04
Can someone help me locate tutorial on how to cascade different authentication schemes and the expected behavior of cascading?

**Comment by emqplus** [comment] 2018-03-04 02:31
@jlgm Yes. The chain is built by the registered order of the authentication module. Notice that the chain only works when usernames are not duplicated in different auth modules.
