### ISSUE TITLE
Send message from paho java client to javascript client

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#552] opened 2016-05-10 01:00 UTC
How can I send a message from paho java client to paho javascript client.

        String topic        = "chatWith/904";
        String content      = "Message from MqttPublishSample";
        int qos             = 0;
        String broker       = "tcp://127.0.0.1:1883";
        String clientId     = "JavaSample";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            System.out.println("Connecting to broker: "+broker);
            sampleClient.connect(connOpts);
            System.out.println("Connected");
            System.out.println("Publishing message: "+content);
            MqttMessage message = new MqttMessage(content.getBytes());
            message.setQos(qos);
            sampleClient.publish(topic, message);
            System.out.println("Message published");
            sampleClient.disconnect();
            System.out.println("Disconnected");
            System.exit(0);
        } catch(MqttException me) {
            me.printStackTrace();
        }

This program run well but i am not receiving any message sent from this client to a javascript client.

Here is JS code

     client = new Messaging.Client(host, Number(port), clientId);

      client.onConnect = onConnect;
  
      client.onMessageArrived = onMessageArrived;
      client.onMessageDelivered = onMessageDelivered;
      client.onConnectionLost = onConnectionLost;            
     var willMessage = createByteMessage({
            id: '',
            'msgType':'USER_STATUS',
            'status': 'Offline',
            'senderId': myUserId,
            'senderName': myName
        }, statusTopic);    
        willMessage.retained = true;  

      client.connect({
        userName:user, 
        password:password, 
        onSuccess:onConnect, 
        onFailure:onFailure,
        'willMessage': willMessage
      }); 

Here port is 8083.

**Comment by xiongtec** [comment] 2016-05-10 13:26
I don't see anywhere in the code about subscribing to a topic.

**Comment by mkj-git** [comment] 2016-05-10 14:49
sorry here i didnt pasted but in my original code its there

**Comment by emqplus** [comment] 2016-06-18 06:40
@mkj-git, the issue is duplicated with #575 and has been fixed in 1.1.1.

**Closed by emqplus** 2016-06-18 06:41 UTC
Labels: Support
